# Generated by Django 5.2.6 on 2025-09-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ragapp.chatsession'),
        ),
    ]
