# Generated by Django 5.2.6 on 2025-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0002_remove_chatmessage_citations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='index_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
